name: trash-seti
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.8
  - jupyter
  - git
  - matplotlib
  - numpy
  - scipy
  - astropy
  - astroquery
  - pandas
  - tqdm
  - pip
  - pip:
      - pycurl
